name: Build test
on:
  workflow_dispatch:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: bash ci.sh deps
    - name: Build LLVM
      run: bash ci.sh llvm
    - name: Build binutils
      run: bash ci.sh binutils
- uses: actions/upload-artifact@v4
  with:
    name: Uploading Clang
    path: /home/runner/work/tc-build/tc-build/install
